### ISSUE TITLE
fatal error C1083: No se puede abrir el archivo incluir: 'cairo.h'

### ISSUE THREAD

**Issue by MarcoAndresito** [napa3um/node-captcha#16]
me sale error al tratar de instalar el modulo

```
C:\Enide-2015-7-windows-x64-20150706\ws\prueba1>npm install captcha
|
> canvas@1.3.12 install C:\Enide-2015-7-windows-x64-20150706\ws\prueba1\node_mod
ules\captcha\node_modules\canvas
> node-gyp rebuild


C:\Enide-2015-7-windows-x64-20150706\ws\prueba1\node_modules\captcha\node_module
s\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_
modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebui
ld )  else (node  rebuild )
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
c:\enide-2015-7-windows-x64-20150706\ws\prueba1\node_modules\captcha\node_modul
es\canvas\src\Canvas.h(19): fatal error C1083: No se puede abrir el archivo inc
luir: 'cairo.h': No such file or directory (..\src\Canvas.cc) [C:\Enide-2015-7-
windows-x64-20150706\ws\prueba1\node_modules\captcha\node_modules\canvas\build\
canvas.vcxproj]
c:\enide-2015-7-windows-x64-20150706\ws\prueba1\node_modules\captcha\node_modul
es\canvas\src\Canvas.h(19): fatal error C1083: No se puede abrir el archivo inc
luir: 'cairo.h': No such file or directory (..\src\ImageData.cc) [C:\Enide-2015
-7-windows-x64-20150706\ws\prueba1\node_modules\captcha\node_modules\canvas\bui
ld\canvas.vcxproj]
c:\enide-2015-7-windows-x64-20150706\ws\prueba1\node_modules\captcha\node_modul
es\canvas\src\Canvas.h(19): fatal error C1083: No se puede abrir el archivo inc
luir: 'cairo.h': No such file or directory (..\src\Image.cc) [C:\Enide-2015-7-w
indows-x64-20150706\ws\prueba1\node_modules\captcha\node_modules\canvas\build\c
anvas.vcxproj]
c:\enide-2015-7-windows-x64-20150706\ws\prueba1\node_modules\captcha\node_modul
es\canvas\src\Canvas.h(19): fatal error C1083: No se puede abrir el archivo inc
luir: 'cairo.h': No such file or directory (..\src\CanvasPattern.cc) [C:\Enide-
2015-7-windows-x64-20150706\ws\prueba1\node_modules\captcha\node_modules\canvas
\build\canvas.vcxproj]
c:\enide-2015-7-windows-x64-20150706\ws\prueba1\node_modules\captcha\node_modul
es\canvas\src\Canvas.h(19): fatal error C1083: No se puede abrir el archivo inc
luir: 'cairo.h': No such file or directory (..\src\CanvasGradient.cc) [C:\Enide
-2015-7-windows-x64-20150706\ws\prueba1\node_modules\captcha\node_modules\canva
s\build\canvas.vcxproj]
c:\enide-2015-7-windows-x64-20150706\ws\prueba1\node_modules\captcha\node_modul
es\canvas\src\Canvas.h(19): fatal error C1083: No se puede abrir el archivo inc
luir: 'cairo.h': No such file or directory (..\src\init.cc) [C:\Enide-2015-7-wi
ndows-x64-20150706\ws\prueba1\node_modules\captcha\node_modules\canvas\build\ca
nvas.vcxproj]
c:\enide-2015-7-windows-x64-20150706\ws\prueba1\node_modules\captcha\node_modul
es\canvas\src\Canvas.h(19): fatal error C1083: No se puede abrir el archivo inc
luir: 'cairo.h': No such file or directory (..\src\CanvasRenderingContext2d.cc)
 [C:\Enide-2015-7-windows-x64-20150706\ws\prueba1\node_modules\captcha\node_mod
ules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Enide-2015-7-windows-x64-20150706\ws\prueba1\node_modules\captch
a\node_modules\canvas
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "captcha"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.12 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Enide-2015-7-windows-x64-20150706\ws\prueba1\npm-debug.log

C:\Enide-2015-7-windows-x64-20150706\ws\prueba1>
```

como podría solucionar esto?

**Comment by polkovnikov-ph** [comment]
1. Read the documentation on `canvas` module. It describes how to install it on Windows. You have to get GTK 2.
2. Consider using Google Translate if you have a bad time speaking English.

**Comment by napa3um** [comment]
Canvas updated.
